# Generated by Django 5.2.9 on 2025-12-22 06:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('amount', 'Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
