# Generated by Django 5.2.9 on 2025-12-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_rename_price_invoiceitem_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount_type',
            field=models.CharField(choices=[('percent', '%'), ('amount', '₹')], default='percent', max_length=10),
        ),
    ]
