# Generated by Django 5.2.9 on 2025-12-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_invoice_subtotal_remove_invoice_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='UNPAID', max_length=20),
        ),
    ]
