# Generated by Django 5.2.9 on 2025-12-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
