# Generated by Django 5.2.8 on 2025-12-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='note',
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CARD', 'Card')], default='CASH', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='date',
            field=models.DateField(),
        ),
    ]
